### ISSUE TITLE
Request - Impersonate on swipe

### ISSUE THREAD

**Issue by CygnusXGithub** [LenAnderson/SillyTavern-UserSwipes#1]
along with the user swipe being made, an option or default capability that does /impersonate. Swiping on User message begins to auto generate. Streaming the content in like character messages do, basically replicating their swipe function's generation

**Comment by LenAnderson** [comment]
Pretty much the same:
```stscript
/imp await=true What's the meaning of life? |
/swipes-add {{input}} ||
/setinput |
```
(/swipes-add from LALib)

**Comment by CygnusXGithub** [comment]
Thanks Len, that put me on the right track as I had been scratching my head trying to make it all work. Your extensions do great!

What got this working 100% for me was hiding the previous message on top of what you provided. So Hide last, gen, unhide, then add swipe and set to input.

/hide {{lastMessageId}} | 
/imp await=true | 
/unhide {{lastMessageId}} | 
/swipes-add {{input}} || 
/setinput |

Note: Both LALib and UserSwipes extensions are needed
